### PR TITLE
Manage ptr:record objects

### PR DESCRIPTION
**Pull request by clementtrebuchet**
SUMMARY
It seems that your `Flask Infoblox Server` from the test container: 
https://github.com/ansible/nios-test-container/blob/master/flaskapp.py  
*does not handle the record:ptr object*

```python
[]
127.0.0.1 - - [03/Jul/2018 20:13:24] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=host.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000&_proxy_search=GM HTTP/1.1" 200 -
# METHOD: POST VIEWTYPE: record:ptr
# REQARGS ...
{}
# REQJSON ...
{'ipv4addr': '192.168.10.1', 'ptrdname': 'host.ansible.com'}
# CREATE VIEWTYPE: record:ptr
########### VIEWTYPE: record:ptr
127.0.0.1 - - [03/Jul/2018 20:13:25] "POST /wapi/v2.1/record%3Aptr HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/clement/Documents/PROJECTS/ansible_env_setup/ansible/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/clement/Documents/PROJECTS/playbooks/nios_ansible_ptr_module/nios-test-container/flaskapp.py", line 407, in v21_base
    view = DATA.create_view(request.get_json(), viewtype=viewtype)
  File "/home/clement/Documents/PROJECTS/playbooks/nios_ansible_ptr_module/nios-test-container/flaskapp.py", line 240, in create_view
    self.views[viewtype].append(view)
KeyError: 'record:ptr'
```
Managing the record:ptr  did the trick.

*The Integration and target tests pass*

```bash
(venv) [clement@clemo nios_ansible_ptr_module]$ ansible-playbook -i inventory  nios_ptr_record_test_playbook.yml  --e="ansible_python_interpreter=$(which python)" 

PLAY [DNS] *********************************************************************************************************************************************************************

TASK [nios_ptr : create an ipv4 ptr record name=ptr.ansible.com, ptrdname=ptr.ansible.com, ipv4=192.168.10.1, state=present, provider={{ nios_provider }}, view=default] *******
Wednesday 04 July 2018  01:42:54 +0200 (0:00:00.228)       0:00:00.228 ******** 
changed: [127.0.0.1]

TASK [nios_ptr : create the same ipv4 ptr record name=ptr.ansible.com, ptrdname=ptr.ansible.com, ipv4=192.168.10.1, state=present, view=default, provider={{ nios_provider }}] ***
Wednesday 04 July 2018  01:42:55 +0200 (0:00:01.007)       0:00:01.235 ******** 
ok: [127.0.0.1]

TASK [nios_ptr : add a comment to an existing ipv4 ptr record name=ptr.ansible.com, ptrdname=ptr.ansible.com, ipv4=192.168.10.1, comment=this is a test comment, state=present, provider={{ nios_provider }}] ***
Wednesday 04 July 2018  01:42:56 +0200 (0:00:00.871)       0:00:02.106 ******** 
changed: [127.0.0.1]

TASK [nios_ptr : add the same comment to the same ipv4 ptr host record name=ptr.ansible.com, ptrdname=ptr.ansible.com, ipv4=192.168.10.1, comment=this is a test comment, state=present, provider={{ nios_provider }}] ***
Wednesday 04 July 2018  01:42:57 +0200 (0:00:00.843)       0:00:02.950 ******** 
ok: [127.0.0.1]

TASK [nios_ptr : remove a ptr record from the system name=ptr.ansible.com, ptrdname=ptr.ansible.com, ipv4=192.168.10.1, state=absent, provider={{ nios_provider }}] ************
Wednesday 04 July 2018  01:42:58 +0200 (0:00:00.866)       0:00:03.817 ******** 
changed: [127.0.0.1]

TASK [nios_ptr : remove the same ptr record from the system ptrdname=ptr.ansible.com, name=ptr.ansible.com, ipv4=192.168.10.1, state=absent, provider={{ nios_provider }}] *****
Wednesday 04 July 2018  01:42:59 +0200 (0:00:00.835)       0:00:04.652 ******** 
ok: [127.0.0.1]

TASK [nios_ptr : assert that=['ipv4_ptr_create1.changed', 'not ipv4_ptr_create2.changed', 'ipv4_ptr_update1.changed', 'not ipv4_ptr_update2.changed', 'ipv4_ptr_delete1.changed', 'not ipv4_ptr_delete2.changed']] ***
Wednesday 04 July 2018  01:42:59 +0200 (0:00:00.855)       0:00:05.508 ******** 
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************************************************************************************************************
127.0.0.1                  : ok=7    changed=3    unreachable=0    failed=0   

Wednesday 04 July 2018  01:42:59 +0200 (0:00:00.077)       0:00:05.585 ******** 
=============================================================================== 
nios_ptr : create an ipv4 ptr record ------------------------------------------------------------------------------------------------------------------------------------ 1.01s
nios_ptr : create the same ipv4 ptr record ------------------------------------------------------------------------------------------------------------------------------ 0.87s
nios_ptr : add the same comment to the same ipv4 ptr host record -------------------------------------------------------------------------------------------------------- 0.87s
nios_ptr : remove the same ptr record from the system ------------------------------------------------------------------------------------------------------------------- 0.86s
nios_ptr : add a comment to an existing ipv4 ptr record ----------------------------------------------------------------------------------------------------------------- 0.84s
nios_ptr : remove a ptr record from the system -------------------------------------------------------------------------------------------------------------------------- 0.84s
nios_ptr : assert ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.08s
Playbook run took 0 days, 0 hours, 0 minutes, 5 seconds
(venv) [clement@clemo nios_ansible_ptr_module]$ 
```
*As well in the fake infoblox server*

```bash
(venv) [root@clemo clement]# python /home/clement/Documents/PROJECTS/playbooks/nios_ansible_ptr_module/nios-test-container/flaskapp.py
 * Serving Flask app "flaskapp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[]
[]
[]
127.0.0.1 - - [04/Jul/2018 01:42:55] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_proxy_search': 'GM',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[]
[]
[]
127.0.0.1 - - [04/Jul/2018 01:42:55] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000&_proxy_search=GM HTTP/1.1" 200 -
# METHOD: POST VIEWTYPE: record:ptr
# REQARGS ...
{}
# REQJSON ...
{'ipv4addr': '192.168.10.1',
 'name': 'ptr.ansible.com',
 'ptrdname': 'ptr.ansible.com',
 'view': 'default'}
# CREATE VIEWTYPE: record:ptr
########### VIEWTYPE: record:ptr
# CREATED VIEW ...
{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
 'comment': None,
 'extattrs': {},
 'fqdn': None,
 'ipv4addr': '192.168.10.1',
 'ipv4addrs': [],
 'ipv6addr': None,
 'ipv6addrs': [],
 'is_default': False,
 'name': 'ptr.ansible.com',
 'network': None,
 'network_view': 'default',
 'options': [],
 'ptrdname': 'ptr.ansible.com',
 'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
 'view': 'default',
 'viewtype': 'record:ptr'}
127.0.0.1 - - [04/Jul/2018 01:42:55] "POST /wapi/v2.1/record%3Aptr HTTP/1.1" 201 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[<__main__.NetworkView object at 0x7f717ec6f860>]
['ptr.ansible.com']
[{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
  'comment': None,
  'extattrs': {},
  'fqdn': None,
  'ipv4addr': '192.168.10.1',
  'ipv4addrs': [],
  'ipv6addr': None,
  'ipv6addrs': [],
  'is_default': False,
  'name': 'ptr.ansible.com',
  'network': None,
  'network_view': 'default',
  'options': [],
  'ptrdname': 'ptr.ansible.com',
  'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
  'view': 'default',
  'viewtype': 'record:ptr'}]
127.0.0.1 - - [04/Jul/2018 01:42:56] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[<__main__.NetworkView object at 0x7f717ec6f860>]
['ptr.ansible.com']
[{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
  'comment': None,
  'extattrs': {},
  'fqdn': None,
  'ipv4addr': '192.168.10.1',
  'ipv4addrs': [],
  'ipv6addr': None,
  'ipv6addrs': [],
  'is_default': False,
  'name': 'ptr.ansible.com',
  'network': None,
  'network_view': 'default',
  'options': [],
  'ptrdname': 'ptr.ansible.com',
  'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
  'view': 'default',
  'viewtype': 'record:ptr'}]
127.0.0.1 - - [04/Jul/2018 01:42:57] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# REFPATH: ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# METHOD: PUT VIEWTYPE: record:ptr UID: false _REFID: record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# REQARGS ...
{}
# REQJSON ...
{'comment': 'this is a test comment',
 'ipv4addr': '192.168.10.1',
 'name': 'ptr.ansible.com',
 'ptrdname': 'ptr.ansible.com'}
# UPDATING REFID record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# network/ZG5zLm5ldHdvcmtfdmlldyQw:1.0.0.0/24/default != record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# network/ZG5zLm5ldHdvcmtfdmlldyQw:1.0.0.0/24/default != record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# network/ZG5zLm5ldHdvcmskZmU4MDo6LzY0LzA:fe80::/64/default != record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# view/ZG5zLnZpZXckTm9uZQ==:default/true != record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false == record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# pk: name pv: ptr.ansible.com
# pk: ipv4addr pv: 192.168.10.1
# pk: ptrdname pv: ptr.ansible.com
# pk: comment pv: this is a test comment
comment is "None" on record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
setting comment to "this is a test comment" on record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false updated? True
# viewk: record:ptr
# viewix: 0
# accessing found view
# return <__main__.NetworkView object at 0x7f717ec6f860>
# MODIFIED VIEW [ZG5zLnJlY29yZDpwdHIkTm9uZQ==] ...
{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
 'comment': 'this is a test comment',
 'extattrs': {},
 'fqdn': None,
 'ipv4addr': '192.168.10.1',
 'ipv4addrs': [],
 'ipv6addr': None,
 'ipv6addrs': [],
 'is_default': False,
 'name': 'ptr.ansible.com',
 'network': None,
 'network_view': 'default',
 'options': [],
 'ptrdname': 'ptr.ansible.com',
 'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
 'view': 'default',
 'viewtype': 'record:ptr'}
127.0.0.1 - - [04/Jul/2018 01:42:57] "PUT /wapi/v2.1/record%3Aptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ%3D%3D%3A1.10.168.192.in-addr.arpa/false HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[<__main__.NetworkView object at 0x7f717ec6f860>]
['ptr.ansible.com']
[{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
  'comment': 'this is a test comment',
  'extattrs': {},
  'fqdn': None,
  'ipv4addr': '192.168.10.1',
  'ipv4addrs': [],
  'ipv6addr': None,
  'ipv6addrs': [],
  'is_default': False,
  'name': 'ptr.ansible.com',
  'network': None,
  'network_view': 'default',
  'options': [],
  'ptrdname': 'ptr.ansible.com',
  'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
  'view': 'default',
  'viewtype': 'record:ptr'}]
127.0.0.1 - - [04/Jul/2018 01:42:58] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[<__main__.NetworkView object at 0x7f717ec6f860>]
['ptr.ansible.com']
[{'_ref': 'record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false',
  'comment': 'this is a test comment',
  'extattrs': {},
  'fqdn': None,
  'ipv4addr': '192.168.10.1',
  'ipv4addrs': [],
  'ipv6addr': None,
  'ipv6addrs': [],
  'is_default': False,
  'name': 'ptr.ansible.com',
  'network': None,
  'network_view': 'default',
  'options': [],
  'ptrdname': 'ptr.ansible.com',
  'uid': 'ZG5zLnJlY29yZDpwdHIkTm9uZQ==',
  'view': 'default',
  'viewtype': 'record:ptr'}]
127.0.0.1 - - [04/Jul/2018 01:42:58] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# REFPATH: ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# METHOD: DELETE VIEWTYPE: record:ptr UID: false _REFID: record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# REQARGS ...
{}
# REQJSON ...
{}
# DELETE VIEW [record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false]
REMOVING record:ptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ==:1.10.168.192.in-addr.arpa/false
# collecting all in record:ptr
[]
127.0.0.1 - - [04/Jul/2018 01:42:58] "DELETE /wapi/v2.1/record%3Aptr/ZG5zLnJlY29yZDpwdHIkTm9uZQ%3D%3D%3A1.10.168.192.in-addr.arpa/false HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[]
[]
[]
127.0.0.1 - - [04/Jul/2018 01:42:59] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000 HTTP/1.1" 200 -
# METHOD: GET VIEWTYPE: record:ptr
# REQARGS ...
{'_max_results': '1000',
 '_proxy_search': 'GM',
 '_return_fields': 'name,view,ipv4addr,ptrdname,ttl,extattrs,comment',
 'ipv4addr': '192.168.10.1',
 'ptrdname': 'ptr.ansible.com'}
# REQJSON ...
{}
# FETCHED VIEW ...
# ARGS ...
# filtering all in record:ptr by name ptr.ansible.com
[]
[]
[]
127.0.0.1 - - [04/Jul/2018 01:42:59] "GET /wapi/v2.1/record%3Aptr?ipv4addr=192.168.10.1&ptrdname=ptr.ansible.com&_return_fields=name%2Cview%2Cipv4addr%2Cptrdname%2Cttl%2Cextattrs%2Ccomment&_max_results=1000&_proxy_search=GM HTTP/1.1" 200 -
```
- This fixes the integration test for the PR: https://github.com/ansible/ansible/pull/41900

ISSUE TYPE
Feature Pull Request
COMPONENT NAME
flaskapp.py

### CODE REVIEW

**Comment by mattclay** [comment]
@clementtrebuchet To make reviewing easier and faster, please limit changes in this PR to the minimum required. Including style related changes in the same PR as functional changes complicates the review process.

Changes to code style are generally discouraged in Ansible repositories when we do not have automated tests in place to enforce style (as we do with the main ansible repository). Once we have enabled style checking for the various test-container repositories we can look at bulk style cleanup, such as with autopep8.

**Comment by clementtrebuchet** [comment]
Seriously? Yes it sees that there is no continuous integration, Just for info, the code does not respect the pep 8, there are also errors in the parameters passed to the function. But no problem I put all this as before. https://github.com/ansible/nios-test-container/blob/master/flaskapp.py#L449

**Comment by clementtrebuchet** [comment]
Hello @mattclay,

I had removed the style related change in the PR.
You would notice that I correct the call to the serialize_view_by_refid method.
Thanks for your support.

image
image

**Comment by justjais** [comment]
@jctanner Can you please review this PR.

**Review by jctanner — APPROVED** [review]

**Pull request merged**
